# Generated by Django 3.2.19 on 2023-07-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_profile_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='communities',
            field=models.ManyToManyField(blank=True, to='learning.Community'),
        ),
    ]
