# Generated by Django 3.2.19 on 2023-07-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_studyplan_communities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='threat',
            new_name='discussion',
        ),
    ]
