# Generated by Django 3.2.19 on 2023-07-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_rename_threat_comment_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='ai_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='suggested_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
