# Generated by Django 3.2.19 on 2023-07-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
