# Generated by Django 3.2.19 on 2023-07-08 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_rename_objectives_section_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.section'),
        ),
    ]
