# Generated by Django 3.2.19 on 2023-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_topic_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='total_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
