# Generated by Django 3.2.19 on 2023-07-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_alter_studyplan_total_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='total_spent',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=5),
        ),
    ]
