# Generated by Django 3.2.19 on 2023-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_studyplan_number_of_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
