# Generated by Django 3.2.19 on 2023-07-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
