# Generated by Django 3.2.19 on 2023-07-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_discussion_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='explanation',
            field=models.TextField(default=''),
        ),
    ]
