# Generated by Django 4.2 on 2023-06-11 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_token_tokenusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 11, 1, 23, 7, 899699, tzinfo=datetime.timezone.utc)),
        ),
    ]
