# Generated by Django 4.2 on 2023-06-14 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_providercredentials_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 21, 38, 55, 145906, tzinfo=datetime.timezone.utc)),
        ),
    ]
