# Generated by Django 4.2 on 2023-06-14 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_alter_token_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 21, 44, 58, 32129, tzinfo=datetime.timezone.utc)),
        ),
    ]
