# Generated by Django 3.2.19 on 2023-06-17 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_auto_20230617_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 23, 50, 36, 152704, tzinfo=utc)),
        ),
    ]
