# Generated by Django 3.2.19 on 2023-06-18 00:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_auto_20230618_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 0, 50, 11, 929359, tzinfo=utc)),
        ),
    ]
