# Generated by Django 3.2.19 on 2023-06-18 01:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_alter_token_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 1, 9, 4, 915819, tzinfo=utc)),
        ),
    ]
