# Generated by Django 3.2.19 on 2023-07-06 20:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_auto_20230706_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 5, 20, 28, 24, 488556, tzinfo=utc)),
        ),
    ]
