# Generated by Django 3.2.19 on 2023-07-10 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0022_auto_20230710_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 13, 6, 51, 816121, tzinfo=utc)),
        ),
    ]
