# Generated by Django 3.2.19 on 2023-07-21 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0027_auto_20230721_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 16, 5, 43, 736634, tzinfo=utc)),
        ),
    ]
