# Generated by Django 4.2 on 2023-06-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitools', '0003_alter_textdocument_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='slug',
            field=models.CharField(help_text='This must be an identificator for the provider', max_length=255),
        ),
    ]
