# Generated by Django 4.2 on 2023-06-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitools', '0005_remove_conversation_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
